---
- name: Set up cgroups and ensure memory controller is active
  hosts: k8s
  become: true
  tasks:
    - name: Install raspberrypi-kernel-headers
      apt:
        name: raspberrypi-kernel-headers
        state: present
        update_cache: yes

    - name: Manually back up cmdline.txt to /tmp/cmdline.txt.backup
      copy:
        src: /boot/firmware/cmdline.txt
        dest: /tmp/cmdline.txt.backup
        remote_src: yes
      tags:
        - cgroup_setup

    - name: Retrieve the PARTUUID of the root partition
      shell: "blkid -s PARTUUID -o value /dev/mmcblk0p2"
      register: root_partuuid
      changed_when: false
      tags:
        - cgroup_setup

    - name: Remove existing duplicate lines from cmdline.txt
      lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: 'root=PARTUUID='
        state: absent
      tags:
        - cgroup_setup

    - name: Ensure the correct PARTUUID is set in cmdline.txt and all parameters are on one line
      lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: '^.*$'
        line: "console=serial0,115200 console=tty1 root=PARTUUID={{ root_partuuid.stdout }} rootfstype=ext4 fsck.repair=yes rootwait systemd.unified_cgroup_hierarchy=1 cgroup_enable=memory cgroup_memory=1"
        state: present
        backrefs: no
      tags:
        - cgroup_setup

    - name: Remove any blank lines in cmdline.txt
      lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: '^\s*$'
        state: absent
      tags:
        - cgroup_setup
