---
- name: Ensure pip3, virtualenv, and required Python packages are installed
  hosts: localhost
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Upgrade all packages
      apt: 
        upgrade: dist
      become: true

    - name: Install required system packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - python3-full
        state: present
      become: true

    - name: Create virtual environment directory if not present
      file:
        path: ~/k3s_venv
        state: directory
        mode: '0755'

    - name: Create virtual environment for Python
      command: python3 -m venv ~/k3s_venv
      args:
        creates: ~/k3s_venv/bin/activate

    - name: Upgrade pip and install required Python packages
      pip:
        name:
          - pip
          - ansible
        state: latest
        virtualenv: ~/k3s_venv

    - name: Install required Python packages using requirements.txt in virtual environment
      pip:
        requirements: "{{ playbook_dir }}/requirements.txt"
        virtualenv: ~/k3s_venv

    - name: Configure pip to use Ansible Galaxy index in virtual environment
      command: "~/k3s_venv/bin/pip config set global.index-url https://galaxy.ansible.com/api/automation-hub/v3/collections/"

    - name: Remove Ansible collection cache directory (if it exists)
      file:
        path: ~/.ansible/collections
        state: absent

    - name: Force install kubernetes.core Ansible collection in virtual environment
      command: "~/k3s_venv/bin/ansible-galaxy collection install kubernetes.core --force"

    - name: Create Ansible configuration directory if it doesn't exist
      file:
        path: /etc/ansible
        state: directory
        mode: '0755'
      become: true

    - name: Check if ansible.cfg exists
      stat:
        path: /etc/ansible/ansible.cfg
      register: ansible_cfg_stat
      become: true

    - name: Backup existing ansible.cfg if it exists
      copy:
        src: /etc/ansible/ansible.cfg
        dest: /etc/ansible/ansible.cfg.bak
        remote_src: yes
      become: true
      when:
        - ansible_cfg_stat.stat.exists

    - name: Ensure collections_path is set in ansible.cfg
      blockinfile: 
        path: /etc/ansible/ansible.cfg
        block: |
          [defaults]
          collections_path = /home/raccoon/.ansible/collections:/usr/share/ansible/collections
        create: yes
      become: true

    - name: Verify pip3 installation in virtual environment
      command: ~/k3s_venv/bin/pip --version
      register: pip_version
      ignore_errors: yes

    - name: Display pip3 version in virtual environment
      debug:
        msg: "pip3 version (virtualenv): {{ pip_version.stdout }}"

    - name: Verify kubernetes Python package installation in virtual environment
      command: ~/k3s_venv/bin/pip show kubernetes
