---
- name: Ensure pip3, virtualenv, and required Python packages are installed
  hosts: localhost
  tasks:

    - name: Activate virtual environment (using environment keyword)
      ansible.builtin.shell:
        cmd: echo "Virtual Environment Activated"
      environment:
        PATH: "~/k3s_venv/bin:{{ ansible_env.PATH }}"

    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install required system packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - python3-full
        state: present
      become: true

    - name: Create virtual environment directory if not present
      file:
        path: ~/k3s_venv
        state: directory
        mode: '0755'

    - name: Create virtual environment for Python
      command: python3 -m venv ~/k3s_venv
      args:
        creates: ~/k3s_venv/bin/activate

    - name: Install required Python packages using requirements.txt in virtual environment
      pip:
        requirements: "{{ playbook_dir }}/requirements.txt"
        virtualenv: ~/k3s_venv

    - name: Configure pip to use Ansible Galaxy index in virtual environment
      ansible.builtin.command:
        cmd: ~/k3s_venv/bin/pip config set global.index-url https://galaxy.ansible.com/api/automation-hub/v3/collections/

    - name: Remove Ansible collection cache directory (if it exists)
      ansible.builtin.file:
        path: ~/.ansible/collections
        state: absent

    - name: Force install kubernetes.core Ansible collection in virtual environment
      ansible.builtin.command:
        cmd: ~/k3s_venv/bin/ansible-galaxy collection install kubernetes.core --force

    - name: Create Ansible configuration directory if it doesn't exist
      file:
        path: /etc/ansible
        state: directory
        mode: '0755'
      become: true

    - name: Ensure collections_path is set in ansible.cfg
      blockinfile: 
        path: /etc/ansible/ansible.cfg
        block: |
          [defaults]
          collections_path = /home/raccoon/.ansible/collections:/usr/share/ansible/collections
        create: yes
      become: true

    - name: Verify pip3 installation in virtual environment
      command: ~/k3s_venv/bin/pip --version
      register: pip_version
      ignore_errors: yes

    - name: Display pip3 version in virtual environment
      debug:
        msg: "pip3 version (virtualenv): {{ pip_version.stdout }}"

    - name: Verify kubernetes Python package installation in virtual environment
      command: ~/k3s_venv/bin/pip show kubernetes
      register: kubernetes_installed
      ignore_errors: yes

    - name: Display success message if kubernetes package is installed
      debug:
        msg: "Kubernetes Python package installed successfully in virtualenv: {{ kubernetes_installed.stdout }}"

    - name: Set environment variable for activating virtualenv
      set_fact:
        venv_path: "~/k3s_venv"