---
- name: Add virtual environment activation to bashrc and fix PATH for user raccoon
  hosts: localhost
  tasks: # Removed 'become: true'

    - name: Add virtualenv bin directory to PATH in raccoon's .bashrc
      lineinfile:
        path: /home/raccoon/.bashrc
        line: 'export PATH="~/k3s_venv/bin:$PATH"'
        state: present
        create: yes
      become_user: raccoon 

    - name: Add script to activate virtual environment in raccoon's .bashrc
      lineinfile:
        path: /home/raccoon/.bashrc
        line: "source ~/activate_ansible_venv.sh"
        state: present
        create: yes
      become_user: raccoon 

    - name: Create shell script to activate virtual environment
      copy:
        dest: ~/activate_ansible_venv.sh
        content: |
          #!/bin/bash
          source ~/k3s_venv/bin/activate
      become_user: raccoon

    - name: Ensure the script is executable
      file:
        path: ~/activate_ansible_venv.sh
        mode: '0755'
        owner: raccoon
        group: raccoon

    - name: Display success message
      debug:
        msg: "Virtual environment PATH has been added to raccoon's .bashrc and will be prioritized on login."