---
- name: Generate secrets.yml and provide encryption instructions
  hosts: k8s_controlplane[0]
  become: true
  gather_facts: false

  tasks:
    - name: Fetch the K3s node token
      shell: sudo cat /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Create secrets.yml (unencrypted)
      copy:
        content: |
          k3s_node_token: "{{ node_token.stdout }}"
        dest: secrets.yml
        owner: raccoon
        group: raccoon

    - name: Move secrets.yml to current directory
      command: mv secrets.yml {{ playbook_dir }}

    - name: Display manual encryption instructions
      debug:
        msg: >
          secrets.yml has been created and moved to the current directory.
          To encrypt it, run:

          ansible-vault encrypt secrets.yml