---
- name: Generate kubeconfig for K3s Cluster
  hosts: k8s_controlplane[0]  # Target only the first control plane node
  become: true
  gather_facts: false

  tasks:
    - name: Fetch the control plane IP from inventory
      set_fact:
        control_plane_ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

    - name: Fetch the CA certificate from the control plane
      slurp:
        src: /var/lib/rancher/k3s/server/tls/server-ca.crt
      register: ca_cert

    - name: Fetch the client certificate from the control plane
      slurp:
        src: /var/lib/rancher/k3s/server/tls/client-admin.crt
      register: client_cert

    - name: Fetch the client key from the control plane
      slurp:
        src: /var/lib/rancher/k3s/server/tls/client-admin.key
      register: client_key

    - name: Gather necessary variables locally
      set_fact:
        local_ca_cert: "{{ ca_cert.content | b64decode }}"  # Decode the base64-encoded certificate
        local_client_cert: "{{ client_cert.content | b64decode }}"  # Decode the client certificate
        local_client_key: "{{ client_key.content | b64decode }}"  # Decode the client key
      delegate_to: localhost

    - name: Create kubeconfig file using client certificates
      copy:
        content: |
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: "{{ local_ca_cert | b64encode }}"
              server: https://{{ control_plane_ip }}:6443
            name: k3s-cluster
          contexts:
          - context:
              cluster: k3s-cluster
              user: admin
            name: default
          current-context: default
          kind: Config
          preferences: {}
          users:
          - name: admin
            user:
              client-certificate-data: "{{ local_client_cert | b64encode }}"
              client-key-data: "{{ local_client_key | b64encode }}"
        dest: /etc/rancher/k3s/kubeconfig.yaml
        mode: '0644'
      delegate_to: localhost

    - name: Copy kubeconfig to other control plane and worker nodes
      ansible.builtin.copy:
        src: /etc/rancher/k3s/kubeconfig.yaml
        dest: /etc/rancher/k3s/kubeconfig.yaml
        owner: root
        group: root
        mode: '0644'
      delegate_to: "{{ item }}"
      with_items:
        - "{{ groups['k8s_controlplane'] | difference([inventory_hostname]) }}"
        - "{{ groups['k8s_worker'] }}"
