---
- name: Generate and distribute kubeconfig
  hosts: k8s_controlplane[0]
  become: true

  tasks:
    - name: Copy the K3s kubeconfig to a shared location
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /etc/k3s/kubeconfig.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Update kubeconfig server URL to point to controlplane1
      replace:
        path: /etc/k3s/kubeconfig.yaml
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://{{ hostvars[groups["k8s_controlplane"][0]]["ansible_host"] }}:6443'

    - name: Distribute the kubeconfig to other controlplane nodes
      copy:
        src: /etc/k3s/kubeconfig.yaml
        dest: /etc/rancher/k3s/k3s.yaml
      delegate_to: "{{ item }}"
      with_items: "{{ groups['k8s_controlplane'] }}"
