---
- name: Generate kubeconfig for K3s Cluster
  hosts: k8s_controlplane[0]  # Target only the first control plane node
  become: true
  gather_facts: false

  vars_files:
    - secrets.yml

  tasks:
    - name: Fetch the control plane IP from inventory
      set_fact:
        control_plane_ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

    - name: Fetch the CA certificate from the control plane
      slurp:
        src: /var/lib/rancher/k3s/server/tls/server-ca.crt
      register: ca_cert

    - name: Fetch the K3s node token from the control plane
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Gather necessary variables locally
      set_fact:
        local_ca_cert: "{{ ca_cert.content | b64decode }}"  # Decode the base64-encoded certificate
        local_node_token: "{{ node_token.content | b64decode | trim }}"  # Decode and trim the token
      delegate_to: localhost

    - name: Create kubeconfig file without extra quotes
      copy:
        content: |
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: "{{ local_ca_cert | b64encode }}"  # Re-encode the certificate properly
              server: https://{{ control_plane_ip }}:6443
            name: k3s-cluster
          contexts:
          - context:
              cluster: k3s-cluster
              user: admin
            name: default
          current-context: default
          kind: Config
          preferences: {}
          users:
          - name: admin
            user:
              token: "{{ local_node_token }}"
        dest: /etc/rancher/k3s/kubeconfig.yaml
        mode: '0644'
      delegate_to: localhost

    - name: Copy kubeconfig to other control plane and worker nodes
      ansible.builtin.copy:
        src: /etc/rancher/k3s/kubeconfig.yaml
        dest: /etc/rancher/k3s/kubeconfig.yaml
        owner: root
        group: root
        mode: '0644'
      delegate_to: "{{ item }}"
      with_items:
        - "{{ groups['k8s_controlplane'] | difference([inventory_hostname]) }}"
        - "{{ groups['k8s_worker'] }}"
