---
- name: Join Worker Nodes to K3s Cluster
  hosts: k8s_worker
  become: true
  gather_facts: false

  tasks:
    - name: Fetch the K3s node token from the control plane
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token
      delegate_to: "{{ groups['k8s_controlplane'][0] }}"
    
    - name: Set the K3s token fact
      set_fact:
        k3s_token: "{{ node_token.content | b64decode | trim }}"

    - name: Join worker node to the cluster
      shell: >
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['k8s_controlplane'][0]]['ansible_host'] }}:6443 \
        K3S_TOKEN={{ k3s_token }} sh -
      args:
        executable: /bin/bash


