---
- name: Configure K3s on control plane nodes
  hosts: k8s_controlplane
  become: true

  tasks:
    - name: Ensure K3s config directory exists
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: '0755'

    - name: Create or update /etc/rancher/k3s/config.yaml
      copy:
        dest: /etc/rancher/k3s/config.yaml
        content: |
          etcd:
            enabled: true
        mode: '0644'
      notify: Restart K3s

    - name: Verify if /etc/rancher/k3s/config.yaml exists
      stat:
        path: /etc/rancher/k3s/config.yaml
      register: k3s_config

    - name: Debug K3s config.yaml content
      debug:
        msg: "{{ k3s_config }}"

  handlers:
    - name: Restart K3s
      service:
        name: k3s
        state: restarted