- name: Fetch K3s token from existing control plane
  hosts: k8s_controlplane[0]  # Run on the first control plane node
  become: true
  gather_facts: false

  tasks:
    - name: Fetch the K3s node token
      shell: sudo cat /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Set the token as a global fact for use in other playbooks
      set_fact:
        k3s_node_token: "{{ node_token.stdout }}"
      delegate_to: localhost

