- name: Prepare Rocky Linux hosts for K3s
  hosts: rocky_nodes
  become: true

  tasks:
    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^/#/' /etc/fstab
      ignore_errors: yes

    - name: Install required packages
      dnf:
        name:
          - curl
          - iptables-services
          - conntrack
          - socat
          - ebtables
          - iproute-tc
        state: present
        update_cache: yes

    - name: Ensure necessary kernel modules are loaded
      shell: |
        modprobe br_netfilter
        echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
        echo '1' > /proc/sys/net/ipv4/ip_forward

    - name: Configure sysctl settings
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{ item }}"
        create: yes
      loop:
        - 'net.bridge.bridge-nf-call-iptables = 1'
        - 'net.ipv4.ip_forward = 1'
      notify: Apply sysctl settings

  handlers:
    - name: Apply sysctl settings
      command: sysctl --system

