---
- name: Output /boot/firmware/cmdline.txt Contents on All Hosts
  hosts: all 
  become: yes
  gather_facts: no

  tasks:
    - name: Read and Display /boot/firmware/cmdline.txt Contents
      ansible.builtin.slurp:
        src: /boot/firmware/cmdline.txt 
      register: file_contents

    - name: Decode the content
      set_fact:
        decoded_content: "{{ file_contents.content | b64decode }}"

    - name: Print cmdline.txt Contents
      debug:
        msg: "Contents of /boot/firmware/cmdline.txt on {{ inventory_hostname }}: {{ decoded_content }}"