---
- name: Generate and encrypt secrets.yml for K3s
  hosts: k8s_controlplane[0]
  become: true
  gather_facts: false

  tasks:
    - name: Fetch the K3s node token
      shell: sudo cat /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Create secrets.yml
      copy:
        content: |
          k3s_node_token: "{{ node_token.stdout }}"
        dest: secrets.yml

    - name: Encrypt secrets.yml
      ansible.builtin.vault:
        action: encrypt
        files: secrets.yml
      # This will now prompt for a vault password
