---
- name: Update /etc/hosts with all hostnames and IPs
  hosts: k8s
  become: yes
  gather_facts: true

  tasks:
    - name: Add all hostnames and IPs to /etc/hosts of each machine
      lineinfile:
        path: /etc/hosts
        regexp: '^.*\s{{ item }}$'  # match lines ending with the current hostname from the loop
        line: "{{ (hostvars[item]['ansible_facts']['default_ipv4']['address'] if 'default_ipv4' in hostvars[item]['ansible_facts'] and hostvars[item]['ansible_facts']['default_ipv4']['address'] is defined else omit) }} {{ item }}"
        insertafter: EOF
        state: present
      become: yes
      loop: "{{ groups['all'] }}"
      when: "'default_ipv4' in hostvars[item]['ansible_facts'] and hostvars[item]['ansible_facts']['default_ipv4']['address'] is defined"

    - name: Verify /etc/hosts
      command: cat /etc/hosts
      register: etc_hosts_content
      changed_when: false  # Mark task as unchanged regardless of output
