apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: TFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVSmtha05EUVZJeVowRjNTVUpCWjBsQ1FVUkJTMEpuWjNGb2EycFBVRkZSUkVGcVFXcE5VMFYzU0hkWlJGWlJVVVJFUW1oeVRUTk5kR015Vm5rS1pHMVdlVXhYVG1oUlJFVXpUV3BaZWs1VVFYcE9SRkYzU0doalRrMXFVWGRQVkVVd1RXcEZNRTVVVVRCWGFHTk9UWHBSZDA5VVJYbE5ha1V3VGxSUk1BcFhha0ZxVFZORmQwaDNXVVJXVVZGRVJFSm9jazB6VFhSak1sWjVaRzFXZVV4WFRtaFJSRVV6VFdwWmVrNVVRWHBPUkZGM1YxUkJWRUpuWTNGb2EycFBDbEJSU1VKQ1oyZHhhR3RxVDFCUlRVSkNkMDVEUVVGU2VUZFJPRlZaY2pFd1J5OUdNazFLTTNadFpqbFVOVEJEVUhobVNHZFdOblpVYjI1VkwyUlZaMElLTkZScmRtcDJiVE5NYkVWWU1XRm1RV1oyY25Sc1dHRlRiSFYzYVU1cFJYcGxjbFJWT0hrMmFVRTBZMDF2TUVsM1VVUkJUMEpuVGxaSVVUaENRV1k0UlFwQ1FVMURRWEZSZDBSM1dVUldVakJVUVZGSUwwSkJWWGRCZDBWQ0wzcEJaRUpuVGxaSVVUUkZSbWRSVldkeU5VOUpTa016WjB4VloxZHhkbEZZY1Uxa0NuQk9jM2x5Vkd0M1EyZFpTVXR2V2tsNmFqQkZRWGRKUkZKM1FYZFNRVWxuWlZOMk9XbGlNekJVZG5Ob1EwOWthaXRrZUZZeVYxVlJNV2hxYkRaRlNHOEtNV1ZYZDJWNVNFMW1SbU5EU1VoMFZuRmFNV0prVEVKWmEzTmFkaTlsTWtKTmIxSkVTbFl5YkdJNWMyNVJMMEpTUkNzNFFVUkpVREVLTFMwdExTMUZUa1FnUTBWU1ZFbEdTVU5CVkVVdExTMHRMUW89  # Remove double quotes from this line
    server: https://192.168.1.91:6443
  name: k3s-cluster
contexts:
- context:
    cluster: k3s-cluster
    user: admin
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: "SzEwZTcxYTJmN2E4NjQwOWU4MDg5MWFmMTRmY2Y3NjY2YzRiZTA4YTk1YzVjOGYxNTJhNmIzNDg2MDc0ZGZlODJjNzo6c2VydmVyOmFlNThlOTRkMWIwY2IzYzI4MDk4YzM5YmQxMWYwODUyCg=="  # Token will still have quotes
