---
- name: Reboot Raspberry Pi Cluster
  hosts: k8s
  become: yes

  tasks:
    - name: Reboot the hosts
      reboot:
        connect_timeout: 10  # Adjust if needed
        reboot_timeout: 300   # Adjust if needed

    - name: Wait for the hosts to come back online
      wait_for_connection:
        delay: 60
        timeout: 300

    - name: Verify SSH connectivity after reboot
      ansible.builtin.ping:
