---
- name: Uninstall K3s from all nodes
  hosts: all
  become: yes
  tasks:
    - name: Stop K3s service
      systemd:
        name: k3s
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Uninstall K3s
      command: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: yes

    - name: Remove K3s directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rancher/k3s
        - /var/lib/rancher/k3s
        - /usr/local/bin/k3s

    - name: Remove iptables rules created by K3s
      command: iptables-save | grep -v KUBE | iptables-restore
      ignore_errors: yes
