---
- name: Update all packages on Raspberry Pi nodes
  hosts: controlplane1 
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes